import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import assert from 'node:assert/strict'

const base = process.env.PREVIEW_URL || 'http://127.0.0.1:5173'
await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const errors = []
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', permissions: ['clipboard-read', 'clipboard-write'] })
const page = await context.newPage()
page.on('pageerror', error => errors.push(error.message))
page.on('response', response => { if (response.status() >= 400 && response.url().startsWith(base)) errors.push(`${response.status()} ${response.url()}`) })
const settle = () => page.waitForTimeout(1500)
const navigate = async name => { await page.getByRole('link', { name: name === 'Work' ? /^Work/ : name, exact: true }).click(); await settle() }
const closeDialog = async () => { await page.keyboard.press('Escape'); assert.ok(!await page.locator('.project-dialog').isVisible()) }

try {
  await page.goto(base, { waitUntil: 'domcontentloaded' })
  await page.locator('.garden-intro').waitFor({ state: 'visible' })
  assert.equal(await page.locator('#smooth-wrapper').evaluate(node => node.inert), true)
  await page.waitForTimeout(1600)
  await page.screenshot({ path: 'artifacts/intro-light.png' })
  assert.ok(await page.locator('canvas').evaluate(canvas => canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data.some(value => value !== 0)), 'The name garden renders')
  await page.locator('.garden-intro').waitFor({ state: 'detached' })
  await settle()
  assert.equal(await page.evaluate(() => document.body.style.overflow), '')
  assert.equal(await page.locator('#home').evaluate(node => node === document.activeElement), true)
  await page.screenshot({ path: 'artifacts/desktop-hero.png' })
  await navigate('Explore my work')
  assert.equal(await page.locator('.cover-card').count(), 4)
  assert.ok(Math.abs((await page.locator('#work').boundingBox()).y) < 3, 'Gallery pins beneath fixed navigation')
  assert.ok((await page.locator('.cover-card').first().boundingBox()).y > 80)
  await page.screenshot({ path: 'artifacts/desktop-work.png' })
  await page.getByRole('button', { name: 'View Pet Finder project', exact: true }).click()
  assert.equal(await page.locator('.project-dialog h2').textContent(), 'Pet Finder')
  assert.equal(await page.locator('.dialog-store-links a').count(), 2)
  await page.screenshot({ path: 'artifacts/project-dialog.png' })
  await closeDialog()
  assert.ok(await page.locator('.cover-card').first().evaluate(node => node === document.activeElement))
  for (let i = 0; i < 3; i++) { await page.getByRole('button', { name: 'Next selected project' }).click(); await settle() }
  assert.equal(await page.locator('.gallery-controls > span').textContent(), '04 / 04')
  const lastCover = await page.locator('.cover-card').last().boundingBox()
  assert.ok(lastCover.x > 0 && lastCover.x + lastCover.width <= 1441, 'Final cover is fully reachable')
  await page.getByRole('button', { name: 'View Elara project', exact: true }).click()
  assert.equal(await page.locator('.project-dialog h2').textContent(), 'Elara')
  await closeDialog()

  await navigate('All projects')
  assert.equal(await page.locator('.slider-card').count(), 17)
  await page.screenshot({ path: 'artifacts/desktop-slider.png' })
  await page.getByRole('button', { name: 'Previous project', exact: true }).click()
  await page.waitForTimeout(750)
  assert.match(await page.locator('.slider-controls').textContent(), /17 \/ 17 PetSchool/)
  await page.locator('.slider-petschool').click()
  assert.equal(await page.locator('.project-dialog h2').textContent(), 'PetSchool')
  assert.match(await page.locator('.dialog-store-links a').getAttribute('href'), /6771285946/)
  await closeDialog()
  await page.getByRole('button', { name: 'Next project', exact: true }).click()
  await page.waitForTimeout(750)
  assert.match(await page.locator('.slider-controls').textContent(), /01 \/ 17 Pet Finder/)
  await page.locator('.slider-petfinder').focus()
  await page.keyboard.press('ArrowRight')
  await page.waitForTimeout(750)
  assert.equal(await page.locator('.slider-mrbrush').evaluate(node => node === document.activeElement), true)
  const bounds = await page.locator('.slider-viewport').boundingBox()
  await page.mouse.move(720, bounds.y + 140)
  await page.mouse.down()
  await page.mouse.move(380, bounds.y + 140, { steps: 20 })
  await page.mouse.up()
  await page.waitForTimeout(750)
  assert.match(await page.locator('.slider-controls').textContent(), /03 \/ 17 Cabuno/)
  assert.ok(!await page.locator('.project-dialog').isVisible(), 'Dragging does not open a project')
  await page.screenshot({ path: 'artifacts/after-slider-drag.png' })
  assert.ok((await page.locator('.archive-toolbar').boundingBox()).y > 80, 'Carousel interaction preserves page position')
  await navigate('All projects')
  for (const [category, count] of [['Extensions', 3], ['Web', 3], ['Mobile', 11], ['All', 17]]) {
    await page.getByRole('button', { name: new RegExp(`^${category}\\s*${count}$`) }).click()
    assert.equal(await page.locator('.slider-card').count(), count)
    assert.match(await page.locator('.slider-controls').textContent(), new RegExp(`01 / ${String(count).padStart(2, '0')}`))
    await page.getByRole('button', { name: 'Previous project', exact: true }).click()
    await page.waitForTimeout(750)
    assert.match(await page.locator('.slider-controls').textContent(), new RegExp(`${String(count).padStart(2, '0')} / ${String(count).padStart(2, '0')}`))
  }

  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await navigate('Let’s talk')
  await page.getByRole('button', { name: 'Copy email address' }).click()
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'hetwork0312@gmail.com')
  await page.screenshot({ path: 'artifacts/footer-dark.png' })
  await page.getByRole('button', { name: 'Replay intro' }).click()
  await page.waitForTimeout(1700)
  await page.screenshot({ path: 'artifacts/intro-dark.png' })
  await page.keyboard.press('Escape')
  await page.locator('.garden-intro').waitFor({ state: 'detached' })
  await page.reload({ waitUntil: 'networkidle' })
  assert.equal(await page.locator('.garden-intro').count(), 0, 'Intro only plays once per session unless replayed')
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  const pdf = await context.request.get(`${base}/het-resume.pdf`)
  assert.equal((await pdf.body()).subarray(0, 4).toString(), '%PDF')

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await page.waitForTimeout(250)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No page overflow at ${width}px`)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await navigate('Work')
  assert.equal(await page.getByRole('button', { name: 'Open navigation' }).getAttribute('aria-expanded'), 'false')
  assert.ok(!await page.locator('#work').evaluate(node => node.parentElement.classList.contains('pin-spacer')), 'Reduced motion uses native horizontal scrolling')
  await page.getByRole('button', { name: 'Next selected project' }).click()
  assert.ok(await page.locator('.selected-viewport').evaluate(node => node.scrollLeft > 100))
  await page.screenshot({ path: 'artifacts/mobile-work.png' })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await navigate('All projects')
  await page.screenshot({ path: 'artifacts/mobile-slider.png' })
  await page.getByRole('button', { name: 'Next project', exact: true }).click()
  assert.match(await page.locator('.slider-controls').textContent(), /02 \/ 17 Mr\. Brush/)
  await page.getByRole('button', { name: 'Previous project', exact: true }).click()
  assert.match(await page.locator('.slider-controls').textContent(), /01 \/ 17 Pet Finder/)
  await page.locator('.slider-petfinder').click()
  await closeDialog()
  await page.screenshot({ path: 'artifacts/mobile-full.png', fullPage: true })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await navigate('Work')
  await page.getByRole('button', { name: 'Next selected project' }).click()
  await settle()
  assert.ok(await page.locator('.selected-viewport').evaluate(node => node.scrollLeft > 100), 'Mobile gallery works with normal motion')
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await navigate('Let’s talk')
  await page.getByRole('button', { name: 'Replay intro' }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: 'artifacts/intro-mobile.png' })
  await page.getByRole('button', { name: 'Skip intro' }).click()
  await page.locator('.garden-intro').waitFor({ state: 'detached' })
  assert.deepEqual(errors, [])
  console.log('Passed: animated intro, skip/replay/session behavior, all four selected covers, infinite wrapping, drag, keyboard focus, filters, dialogs, theme persistence, reduced motion, five responsive sizes, clipboard, resume, runtime and assets.')
} finally { await browser.close() }
