import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import assert from 'node:assert/strict'

await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const errors = []
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', permissions: ['clipboard-read', 'clipboard-write'] })
const page = await context.newPage()
page.on('pageerror', error => errors.push(error.message))
page.on('response', response => { if (response.status() >= 400 && response.url().startsWith('http://127.0.0.1')) errors.push(`${response.status()} ${response.url()}`) })
await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' })
await page.waitForTimeout(1700)
await page.screenshot({ path: 'artifacts/desktop-hero.png' })
assert.equal(await page.locator('h1').count(), 1)
assert.equal(await page.locator('.project-card').count(), 4)
await page.getByRole('link', { name: 'Explore my work' }).click()
await page.waitForTimeout(1400)
assert.ok(Math.abs((await page.locator('#work').boundingBox()).y - 90) < 15, 'Work anchor aligns below header')
await page.screenshot({ path: 'artifacts/desktop-work.png' })
await page.locator('.project-card').filter({ hasText: 'Pet Finder' }).click()
assert.ok(await page.getByRole('dialog').isVisible())
assert.equal(await page.getByRole('dialog').getByRole('heading', { level: 2 }).textContent(), 'Pet Finder')
assert.match(await page.getByRole('dialog').getByRole('link').getAttribute('href'), /com.brilworks.petfinder/)
await page.screenshot({ path: 'artifacts/project-dialog.png' })
await page.keyboard.press('Escape')
assert.ok(!(await page.getByRole('dialog').isVisible()))
assert.ok(await page.locator('.project-card').filter({ hasText: 'Pet Finder' }).evaluate(element => element === document.activeElement))
await page.getByRole('link', { name: 'All projects', exact: true }).click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: /Extensions\s*3/ }).click()
assert.equal(await page.locator('.archive-card').count(), 3)
assert.match(await page.locator('.archive-grid').textContent(), /Nudge/)
await page.getByRole('button', { name: /Web\s*3/ }).click()
assert.equal(await page.locator('.archive-card').count(), 3)
await page.getByRole('button', { name: /Daliy.tools/ }).click()
assert.equal(await page.getByRole('dialog').getByRole('link').getAttribute('href'), 'https://daliy.tools/')
await page.getByRole('button', { name: 'Close project' }).click()
await page.getByRole('button', { name: /All\s*16/ }).click()
assert.equal(await page.locator('.archive-card').count(), 6)
await page.getByRole('button', { name: 'See all 16 projects' }).click()
assert.equal(await page.locator('.archive-card').count(), 16)
await page.getByRole('button', { name: 'Show fewer projects' }).click()
assert.equal(await page.locator('.archive-card').count(), 6)
await page.getByRole('button', { name: 'Switch to dark theme' }).click()
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
await page.getByRole('link', { name: 'Het Patel, home' }).click()
await page.waitForTimeout(1200)
await page.screenshot({ path: 'artifacts/desktop-dark.png' })
await page.reload({ waitUntil: 'networkidle' })
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
await page.getByRole('link', { name: 'Let’s talk', exact: true }).click()
await page.waitForTimeout(1300)
await page.getByRole('button', { name: 'Copy email address' }).click()
assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'hetwork0312@gmail.com')
assert.equal(await page.locator('.copy-status').textContent(), 'Email copied')
const pdf = await context.request.get('http://127.0.0.1:5173/het-resume.pdf')
assert.equal(pdf.status(), 200)
assert.equal((await pdf.body()).subarray(0, 4).toString(), '%PDF')
await page.emulateMedia({ reducedMotion: 'reduce' })
await page.getByRole('button', { name: 'Switch to light theme' }).click()
await page.getByRole('link', { name: 'Het Patel, home' }).click()
await page.screenshot({ path: 'artifacts/desktop-full.png', fullPage: true })
for (const width of [320, 390, 768, 1024, 1440]) {
  await page.setViewportSize({ width, height: 844 })
  await page.waitForTimeout(200)
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No overflow at ${width}px`)
}
await page.setViewportSize({ width: 390, height: 844 })
await page.getByRole('button', { name: 'Open navigation' }).click()
assert.equal(await page.getByRole('button', { name: 'Close navigation' }).getAttribute('aria-expanded'), 'true')
await page.getByRole('link', { name: 'About', exact: true }).click()
assert.equal(await page.getByRole('button', { name: 'Open navigation' }).getAttribute('aria-expanded'), 'false')
assert.ok((await page.locator('#about').boundingBox()).y >= 60)
await page.getByRole('link', { name: 'Het Patel, home' }).click()
await page.screenshot({ path: 'artifacts/mobile-hero.png' })
await page.screenshot({ path: 'artifacts/mobile-full.png', fullPage: true })
assert.deepEqual(errors, [])
console.log('Passed: desktop/mobile layout, navigation, project dialog and focus restoration, filters, expansion, theme persistence, reduced motion, clipboard, resume PDF, and runtime/asset checks.')
await browser.close()
